### ISSUE TITLE
Could it handle bot's token ?

### ISSUE THREAD

**Issue by Ximaz** [LucunJi/kaiheila-musicbot#1]
Hi,
Someone successfully made [binaries to handle a bot token](https://www.npmjs.com/package/khl-voice) and then make it play audio in a voice channel. But there is no source code of this project. It uses something called krust-voice 0.1. It also seems to use ffmpeg since it requires an ffmpeg path. Any idea how it could work ? It could be nicer than trying to login to my account to play audio as me and not as bot.

**Comment by LucunJi** [comment]
Sorry I have no idea about krust-voice. Also I guess ffmpeg is used to handle music, and do things such as decoding and playing music. I use mpg123 and pactl in this prject for the same purpose.

This project is discontinued because I do have enough time and patience to keep working on it. Plus there are official ways to manipulate voice channels so you can take this project to be obsoleted.

**Comment by LucunJi** [comment]
By the way, if your requirement is to
> It could be nicer than trying to login to my account to play audio as me and not as bot.

Then you just need to learn to use pactl (for Linux) or virtual cable (for Windows) to redirect the music on your own PC. My project aims to play music as a bot (or a userbot, before official support came out). A centralized bot suits better when everyone uses the voice channel equally, while your idea, if I guess correctly, fits into the scenario when one streamer uses the voice channel for the most of the time.

**Comment by Ximaz** [comment]
There is not offical way that came pour nowadays, we still need to wait.

Thanks for the pactl reference. :)
